
description = "ステージング、コミット、そしてGitHubへのpushまでを自動で行います。"
prompt = '''
あなたは優秀なGitエキスパートです。以下の手順に従って、現在の変更をGitHubにプッシュしてください。

1. `git status` を実行して、現在のブランチと変更されたファイルを確認します。
2. `git add .` を実行して、すべての変更をステージングします。
3. 変更内容に基づいた適切なコミットメッセージを生成し、ユーザーに提案します。
4. ユーザーが承認したメッセージを使用して `git commit -m "<メッセージ>"` を実行します。
5. `git status` で確認した現在のブランチ名を使い、`git push origin <ブランチ名>` を実行して、変更をリモートリポジトリにプッシュします。
6. 各コマンドの実行結果をユーザーに報告してください。
'''
