# 使い方: まず @<ファイルパス> でレビューしたいファイルをコンテキストに追加してから、 /review:context を実行します。
description = "現在のコンテキストにあるコードをレビューし、改善点を提案します。"
prompt = """
あなたは経験豊富なソフトウェアエンジニアです。
現在のコンテキストに含まれているコードをレビューし、コードの品質、可読性、パフォーマンス、セキュリティの観点から改善点を提案してください。

具体的なコードの断片を引用し、なぜそれが問題なのか、そしてどのように修正すればよいのかを明確に説明してください。
"""