# 呼び出し方: /explain:shell <説明してほしいシェルコマンド>
description = "指定されたシェルコマンドが何をするのかを説明します。"
prompt = """
以下のシェルコマンドについて、各部分が何をしているのか、そしてコマンド全体としてどのような目的を達成しようとしているのかを、初心者にも分かりやすく説明してください。

コマンド: `{{args}}`
"""