# 呼び出し方:
# 1. テキストで要件を渡す: /plan:create <開発したい機能の概要>
# 2. ファイルで要件を渡す: /plan:create @<要件定義ファイルのパス.md>
description = "指定された要件（テキストまたはファイル）に基づいて開発計画の草案を作成します。"
prompt = """
あなたは経験豊富なプロジェクトマネージャー兼ソフトウェアエンジニアです。
以下の要件を実現するための、詳細な開発計画を立案してください。

**要件:**
{{args}}

**出力形式:**
Markdown形式で、以下の構成要素を含んだ計画書(TODO.md)を作成してください。

---

### 1. 計画の概要
要件を簡潔にまとめ、この計画が何を達成するためのものかを記述します。

### 2. 主要タスクリスト
実装すべき大きな機能やコンポーネントをリストアップします。

- [ ] 機能A
- [ ] 機能B
- [ ] 機能C

### 3. 詳細タスクのブレークダウン
各主要タスクを、実行可能な具体的なサブタスクに分解します。

#### 機能A
- [ ] サブタスクA-1
- [ ] サブタスクA-2

#### 機能B
- [ ] サブタスクB-1
- [ ] サブタスクB-2

### 4. 考慮事項
実装にあたって注意すべき技術的な課題、UI/UXのポイント、テストの観点などを記述します。

---

ステップバイステップで考え、網羅的で実行可能な計画を立ててください。
"""